name: magangproject
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: 4.15.6
  firebase_storage: 11.6.7
  # url_launcher: 6.2.5
  flutter: 
    sdk: flutter
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

assets: 
  -assets/logo.png
  -assets/verifikasi.png
  -assets/icon.png

