// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIi4s43uq9gbHYtMywHcCQl4du76zjBYk',
    appId: '1:1062069250421:web:173a1fc313dc1cbb428b3c',
    messagingSenderId: '1062069250421',
    projectId: 'magangproject-48d71',
    authDomain: 'magangproject-48d71.firebaseapp.com',
    storageBucket: 'magangproject-48d71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoeGOzvsSpZ_95S8i2eyigtPvpAn0YYHA',
    appId: '1:1062069250421:android:02aad2adf8c7f328428b3c',
    messagingSenderId: '1062069250421',
    projectId: 'magangproject-48d71',
    storageBucket: 'magangproject-48d71.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhAwDwDYhQ4b8KdmAnx_WJ1ZBeHv8hfro',
    appId: '1:1062069250421:ios:73b0f439bb24c4ca428b3c',
    messagingSenderId: '1062069250421',
    projectId: 'magangproject-48d71',
    storageBucket: 'magangproject-48d71.appspot.com',
    iosBundleId: 'com.example.magangproject.RunnerTests',
  );
}
